### ISSUE TITLE
[RFC] Pluggable API documentation generator

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/apispec#1]
Now that smore has many of the lower-level functions for converting marshmallow `Schema` and webargs `Args` to swagger definitions, next step is to implement a system for generating full API docs.

Ideas for initial iteration:
- Based on Swagger 2.0 spec. This will allow us to leverage the latest Swagger-UI
- Pluggable. The documentation generator will work with any web framework, with or without webargs, etc. etc. Plugins provide helpers for generating metadata.
- Easy way to serve swagger docs. Possibly part of the Flask plugin.

Ideas for the future:
- Generate swagger-based from docstrings.
- Sphinx extension?
## Proof of concept

I wrote up a simple proof-of-concept in this gist: https://gist.github.com/sloria/dc1b2d2e43fbcea866ae
## Prior art
- [django-rest-swagger](https://github.com/marcgibbons/django-rest-swagger)
- [flask-restful-swagger](https://github.com/rantav/flask-restful-swagger)
- [flask-restplus](https://github.com/noirbizarre/flask-restplus)
- [cornice](http://cornice.readthedocs.org/en/latest/sphinx.html) (not swagger-based, but may provide ideas for sphinx extension)

**Comment by hello-josh** [comment]
I like the direction this is going in, integrating webargs / marshmallow to handle the minutiae around input and output. One thing that irks me with the current flask-based approaches is that you spend a bunch of time documenting your api but then you still have to manually extract your args from the request (e.g. `args = parser.parse_args()`) and most of them rely on magic dictionaries that match up 1-to-1 with the swagger spec. IMO you end up writing so much code that you wonder what the library is actually buying you in the first place?

Sometimes I think it would be less word to craft the swagger json schema by hand and then pass it into your framework's router and have it enforce, marshal, and pass parsed input directly into your view handler instead of adding decorators on top of decorators.

I guess what I really am getting at is that the current implementations I have seen are not written at a high enough level of abstraction to make them any more useful than implementing it by hand.

**Comment by sloria** [comment]
Thanks for your input @Trii. I agree with your point re: solutions that require you to write your entire Swagger spec manually (in code).

The idea I'm proposing here is that plugins do the work of "writing" your Swagger spec. So if you use no plugins, you write your whole spec. Use Flask? The Flask plugin generates Swagger Paths so you don't have to. Use marshmallow? The marshmallow plugin generates Swagger Schema Objects for you. And so on. You mix and match plugins according to your stack.

**Comment by hello-josh** [comment]
Maybe it is out of the scope of this project/thread but is smore intended to enforce the swagger spec inside around your api as well as generate the documentation for you?

It would be awesome if the plugins would also be able to address the task of extracting arguments from a request (via webargs), unmarshaling them into some application-level objects (via marshmallow), injecting the application level objects into the args for your "view function", then marshal your framework output into the output json format (again via marshmallow) as well.

That is the problem I am starting to solve now via the webapp2 parser I submitted to webargs. If that is on the roadmap for smore, I could take a stab at it here instead.

**Comment by sloria** [comment]
@Trii Sorry for the delayed response. I can't promise that this project will do complete validation against the Swagger spec the development stage. For example, if you pass incorrect arguments to one of the `APISpec` methods, it may not always raise an exception.

That said, the test suite does [validate the output](https://github.com/marshmallow-code/smore/blob/6ac181b121b6dfdab22746aab8b5254f4d7a6d18/tests/swagger/test_swagger.py#L477) of `APISpec`--given _valid_ arguments--using `swagger-tools`.

Re: request parsing and marshalling: webargs should provide all you need (now that it depends on marshmallow). The [use_schema](https://github.com/sloria/webargs/blob/dev/examples/schema_example.py) and [annotations_example](https://github.com/sloria/webargs/blob/dev/examples/annotations_example.py) might be particularly useful to you.

**Comment by sloria** [comment]
Closing for now. Any other design feedback should be opened as new issues.
