### ISSUE TITLE
Support marshmallow-jsonapi

### ISSUE THREAD

**Issue by lycplus** [marshmallow-code/apispec#115]
It is good if we can support marshmallow-jsonapi schema.

**Comment by sloria** [comment]
This is more an issue with marshmallow-jsonapi than apispec. marshmallow-jsonapi relies on `post_dump`/`pre_load` methods for jsonapi formatting, which makes it difficult for apispec to inspect the correct schemas. This issue is documented in marshmallow-code/marshmallow-jsonapi#12. Further discussion should happen on that issue.
