### ISSUE TITLE
Marshmallow schema parameters are resolved using schema class, not schema instance

### ISSUE THREAD

**Issue by dlopuch** [marshmallow-code/apispec#169]
When apispec resolves parameters using marshmallow schemas, it appears to use the Schema *class*, not the Schema *instance*:

https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/__init__.py#L146

I believe this is problematic because Marshmallow allows for schema modifiers on instantiation, but these modifiers are therefore ignored by apispec.  This is important because different uses of a schema may require different instantiations.

For example, say you define a schema like so:

```python
class SomeEntitySchema(Schema):
    id = fields.Integer(required=True)
    name = fields.String(required=True)
```

On a get-item, either the class or the generic instantiation `SomeEntitySchema()` works.  

However, on a post, you would use it as a body param like `SomeEntitySchema(exclude=('id',)` -- ie when you're creating a new entity, you don't pass in the ID (this would be assigned by the server).

So the bug is since apispec uses the *class* of the schema not the *instance* in the parameter case, instance-specific modifiers are ignored.  The apispec tells you that `id` is required on a post, which you specifically said it's not.

Any insight into why https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/__init__.py#L146 looks up the class instead of using the instance?

**Comment by inkhey** [comment]
Just trying something to support exclude/only for auto_ref : https://github.com/inkhey/apispec/commit/e584f26433bcc388267a71292c61add7ee94ae76 .

**Comment by lafrech** [comment]
@dlopuch, for this specific use case, I just mark `id` as `dump_only` in the schema and I can use the same schema class in GET, POST and PUT.

**Comment by lafrech** [comment]
This is a complicated design choice. Indeed it can be misleading to accept instances but resolve on the class. Maybe resolving on instances wouldn't make things worse.

The issue with resolving by instance is that if you use a schema with the same modifiers in multiple places, it won't be the same instance (unless you instantiate it once and re-use the instance) so the definition resolving won't work. But it is not as bad as current situation.

I don't see any obvious blocking issue with resolving by instance. Doesn't mean there is none.

**Comment by lafrech** [comment]
Resolving on class is wrong because it ignores instance modifiers.

Resolving on instances means one would need to register an instance and then reuse that instance in its views. I don't see a elegant way of doing this. We may end up with code like this:

```py
pet_load_schema = PetSchema(exclude=('id',))

spec.definition('PetLoad', pet_load_schema)
```

Then refer to that `pet_load_schema` instance in the code / docstrings.

I don't see a nice way of doing this, but I'm open to suggestions if provided a sample application doing this in a nice fashion.

In practice, I never had to use such modifiers and the example above is a bad example (marking the `id` field `dump_only` would work).

We could leave it as is an add a big warning in the docs against using modifiers.

A third-way approach would be to compare modifiers rather than just the class when resolving. We'd need to be sure that all possible modifiers are checked. At least, checking a subset would be better than nothing.

**Comment by lafrech** [comment]
Here's a draft of `Schema` comparison feature: https://github.com/marshmallow-code/marshmallow/pull/1062.
