### ISSUE TITLE
Support for Hyperlinks schema field type (provided by flask-marshmallow)

### ISSUE THREAD

**Issue by Ch00k** [marshmallow-code/apispec#172]
Currently if I have a `Hyperlinks` field type in my schema, it is being interpreted as `string`, and of course all the complex nested structure of the field is not preserved. Is there any way I can make `Hyperlinks` field type work with apispec?
https://flask-marshmallow.readthedocs.io/en/latest/#flask_marshmallow.fields.Hyperlinks

**Comment by Ch00k** [comment]
Just realised that the same happens to a `Function` field.

**Comment by lafrech** [comment]
This happens in `OpenAPIConverter.field2property`.

There is currently no way to extend this method.

As a workaround, you could make your own `OpenAPIConverter` child class and override `field2property`, then override `MarshmallowPlugin` to use it. This implies a lot of duplication in `field2property`, so it is far from perfect.

A better solution would be to let the user specify `field2property` methods to map to field types, assuming that's even feasible.

We could keep a `FIELD_TO_PROPERTY` mapping:

```py

FIELD_TO_PROPERTY = {
    flask_marshmallow.fields.Hyperlinks: hyperlink_field2property,
}
```
Each methods in the mapping would return a dict.

Then in `OpenAPIConverter.field2property`

```py
        [...]
        elif isinstance(field, marshmallow.fields.Dict):
            [...]
        # Manage custom fields
        elif type(field) in FIELD_TO_PROPERTY:
            ret.update(FIELD_TO_PROPERTY[type(field)](field, use_refs=use_refs, dump=dump, name=name))
        [...]
```

Then, you'd "just" have to create `hyperlink_field2property` so that it returns what you expect.

By definition, `Function` fields can return anything. What would you expect apispec to do?
