### ISSUE TITLE
Add recursive merging in APISpec.to_dict

### ISSUE THREAD

**Issue by b0g3r** [marshmallow-code/apispec#218]
In Open API spec 3.0.1 `securityDefinitions` was renaming and moved to `components`

APISpec class allowed add additional fields to swagger file with kwarg-parameter `options`. I try add `components` with security definition to kwarg, but this rewrite schema definitions (in swagger 3.0.1 schema definitions also in `components`)

Currently in [APISpec.to_dict](https://github.com/marshmallow-code/apispec/blob/dev/apispec/core.py#L167) used dict.update method, but this works without recursion and rewrite nested dict.

How about replace this method to recursive merging (e.g. https://gist.github.com/angstwad/bf22d1822c38a92ec0a9)?

**Comment by b0g3r** [comment]
May be linked with https://github.com/marshmallow-code/apispec/issues/165

**Comment by fMeow** [comment]
I have propose a PR #222 on this issue.  

However, I don't think it necessary to recursively update components object. Instead, this issue just happens because apispec would generate a `components` object with `schemas` and `parameters`. 

And a simpler way is to merge `schemas` and `parameters`, while **copying all other fields** like 'securitySchemes`.

**Comment by sloria** [comment]
This is addressed by #222.
