### ISSUE TITLE
RFC: remove schema auto-reference feature from MarshmallowPlugin

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/apispec#307]
See [comment](https://github.com/marshmallow-code/apispec/pull/179#issuecomment-405185455).

Rationale:

This is something that is easy to do in a custom plugin. Just override `definition_helper`. But it is hard to do in a totally generic way.

To make it more generic, the authors added a `schema_name_resolver` callback, so that the user can provide a function that returns a name from a Schema (for instance, it can be the schema name with Schema suffix removed, and lowercased: `PetSchema` -> `pet`).

The `inspect_schema_for_auto_referencing` method hardcodes the field types that have containers. Currently, only `Nested` and `List`. `Dict` is missing for Marshmallow 3 (this could be easily fixed). And there is no mechanism to allow custom container fields. We could add another parametrization mechanism for that, but it looks like overparametrization. I mean from a user perspective, it looks just as easy to reimplement the whole feature (the recipe can be provided in the docs) than to awkwardly parametrize the existing feature. OTOH, I realize the custom field with container is a corner case.

The PR I linked to above (#179) adds more complexity to fix issues in the feature.

I'm thinking it might be better to drop it. Maybe we could add instructions in the docs to show how to achieve it in a custom plugin. Of course, if the original authors manage to do what they need in a plugin and publish this plugin, I'd be happy to link to it. The point is not to trash other people's work (NIH syndrome), but to make it the most practical both from user and maintainer perspective.

Maybe I'm overthinking it. It's mostly a matter of opinion. I'm open to discussion about it. Since it is a breaking change, I'd like to have it settled for 1.0.

@inkhey, @lebouquetin and @buxx, since you added the feature, I'd be happy to get your feedback. I think you can easily fit this in hapic. It might be even easier for you if you want to modify it. You tell me.

Note: If we keep it, let's at least manage the `Dict` case for marshmallow 3.

**Comment by Bangertm** [comment]
I like the concept behind the auto-reference feature: add a single schema to the spec and all sub schemas get added and referenced.  This keeps the resulting yaml relatively flat and give names to nested schemas instead of nesting them as an anonymous object. 

My concern with the current state of affairs is that nested schemas are handled in two separate code blocks.  One is in [inspect_schema_for_autoreferencing](https://github.com/marshmallow-code/apispec/blob/e8050c5cd2f7240c9693aa15e21c8cb4db1cf8c4/apispec/ext/marshmallow/__init__.py#L66) and the other in [field2property](https://github.com/marshmallow-code/apispec/blob/e8050c5cd2f7240c9693aa15e21c8cb4db1cf8c4/apispec/ext/marshmallow/openapi.py#L337).  

To me ideally instead of deleting the auto-reference functionality, we would make it the default.  For example provide a default implementation of `schema_name_resolver` and merge the functionality of `inspect_for_autoreferencing` and `field2property`.  Perhaps in [fields2jsonschema](https://github.com/marshmallow-code/apispec/blob/e8050c5cd2f7240c9693aa15e21c8cb4db1cf8c4/apispec/ext/marshmallow/openapi.py#L605) - whenever encountering a nested field add a ref in place of the current field and add the nested schema to the main spec.

**Comment by buxx** [comment]
Hello,

Thank you for the global summary of our feature.

> @inkhey, @lebouquetin and @buxx, since you added the feature, I'd be happy to get your feedback. I think you can easily fit this in hapic. It might be even easier for you if you want to modify it. You tell me.

We use this feature in several projects now and it is essential for us. To make a reminder, we use this feature through hapic to permit auto generation of OpenAPI 2.0 doc by adding Marshmallow schemas in view decorators (example [here](https://github.com/algoo/hapic#fast-flask-example)).

We seriously considering making hapic compatible with marshmallow3/apispec 1.x by recoding this feature with a plugin.

About @Bangertm remark, i also like this idea.

**Comment by lafrech** [comment]
Thank you guys for your feedback.

@buxx, if removed from vanilla apispec, I think it can be copied in a plugin and work exactly the same way as it used to, so unless I'm mistaken, your use case wouldn't be broken. And having it in your plugin would even simplify it as you wouldn't need so much customization. For instance, the schema_name_resolver could be hardcoded.

@Bangertm if this is feasible, it would be nice. I don't object to the feature at all. I just find current implementation incomplete and a bit clumsy. But if there is a way to improve it and keep it in apispec, that's even better. Anyone willing to investigate this?

**Comment by buxx** [comment]
@lafrech For information, i'm writing auto-reference feature as a plugin.

**Comment by lafrech** [comment]
@buxx, please have a look at @Bangertm's work on this: https://github.com/marshmallow-code/apispec/pull/333.

We're almost done with this and chances are the feature could be integrated in the core.

It's nice if you can have a look at it and provide feedback. Do you see any issue with his implementation? Anything that would break your use case?

**Comment by buxx** [comment]
I take a look.

**Comment by buxx** [comment]
@lafrech @Bangertm I can say that is it ok for us: 

* Beautiful implementation
* Our code is compatible

Just one thing to say, let's go ^^

**Comment by lafrech** [comment]
Closed by https://github.com/marshmallow-code/apispec/pull/333.
