### ISSUE TITLE
nested load_only fields appears in response

### ISSUE THREAD

**Issue by zeakd** [marshmallow-code/apispec#348]
Hi.

I'm using apispec 1.0.0b6 and I love responses swagger control with load, dump_only fields.
but when schema is nested, load_only fields appears in responses example value.

related #303 #119 
Thanks

**Comment by lafrech** [comment]
With the recent changes in apispec, schemas are automatically references and their definition includes read/write only fields because it may be used both as parameter or response. Therefore, load_only fields always appear in schema definitions.

If you're using OpenAPIv3, they should have the `writeOnly` attribute. This attribute does not exist on OpenAPIv2. One could add `x-writeOnly` to the `Field`, but that would probably not be recognized by any frontend or client.

**Comment by lafrech** [comment]
@zeakd, still stuck on this? May I close this issue?

**Comment by zeakd** [comment]
@lafrech oh, sorry, I missed the notice. I'll reopen this if it's still a problem in our project.
