### ISSUE TITLE
How to implement a custom 'schema_name_resolver'

### ISSUE THREAD

**Issue by Paradoxis** [marshmallow-code/apispec#430]
I'm currently helping apply swagger documentation to a large codebase which uses Marshmallow to serialise objects, the api uses a JSON protocol named [jsend](https://github.com/omniti-labs/jsend), for this I decided to write a plugin which wraps all schema's with a dynamic JSend envelope, however when I do this my console gets spammed with messages along the following:

> UserWarning: Multiple schemas resolved to the name CustomerJsend. The name has been modified. Either manually add each of the schemas with a different name or provide a custom schema_name_resolver.

When looking on the documentation I can't find any trace of a `schema_name_resolver` nor how to use it, after digging through the code of the `MarshmallowPlugin` I saw a few references to it but I couldn't seem to figure out what it was doing.

The following is my plugin:

```python
from apispec import BasePlugin
from apispec.ext.marshmallow import OpenAPIConverter

from marshmallow import Schema, fields
from marshmallow.validate import Range, OneOf


class JSendPlugin(BasePlugin):
    """Base class for APISpec plugin classes."""

    def path_helper(self, path=None, operations=None, **kwargs):
        for method, operation in operations.items():
            for code, response in operation['responses'].items():
                response['schema'] = self.jsend_schema(response['schema'], code)

    def jsend_schema(self, schema, code):
        """
        Converts a regular schema to a JSend schema
        :param schema: Schema to nest
        :param code: HTTP status code (determines the key)
        :return: Updated schema
        """
        name = schema.__class__.__name__.replace('Schema', '')
        key = 'data' if code in range(100, 400) or code == 'default' else 'message'

        props = {
            'code': fields.Int(
                required=True,
                validate=Range(100, 600)
            ),
            'status': fields.Str(
                required=True,
                validate=OneOf(('success', 'error', 'fail'))
            ),
            key: schema
        }

        return type(name + 'JSendSchema', (Schema,), props)
```

Could anyone tell me how to implement the resolver or what I'm doing wrong?

---

I also tried the following, but this led to a JSON serialization issue:

```python
class JSendPlugin(BasePlugin):
    """Base class for APISpec plugin classes."""

    def path_helper(self, path=None, operations=None, **kwargs):
        for method, operation in operations.items():
            for code, response in operation['responses'].items():
                key = 'data' if (
                    code in range(100, 400)
                    or code == 'default'
                ) else 'message'

                response['schema'] = {
                    'code': {
                        'type': 'integer',
                        'format': 'int32',
                    },
                    'status': {
                        'type': 'string',
                        'enum': [
                            'success',
                            'error',
                            'fail',
                        ]
                    },
                    key: response['schema']
                }
```

**Comment by Bangertm** [comment]
I think what is happening in the first example is that for each status code the plugin is creating a new envelope schema class and that multiple envelope classes have the same `__name__`.  When adding different schema classes to the spec that have the same `__name__`, APISpec will create a unique name by appending  an integer to the name and provide a warning a warning because this is likely not what you want.  I.e. if you look at the generated spec you will probably see multiple schemas named `CustomerJsend`, `CustomerJsend1`, `CustomerJsend2`, etc.  The reason that you likely would not want this is because if you have two routes that return a `CustomerSchema` wrapped in a JSend envelope one will reference `CustomerJsend` and the other will reference `CustomerJsend1` even though they are both the same data structure.  

What you are going to want to do is to add the _same_ envelope class to the spec for every route and response code in your api.  This way you will get JSON reference objects in each route/code that point to a single schema definition.  

I presume that you have not already defined schema classes that look like JSend wrappers for each schema in the api.  If you did you could just put those in your docstring YAML and things should work.  

Given that it seems that you want to do this dynamically as part of the documentation, I would probably recommend adding a property to `JSendPlugin` that what would be a dictionary with the wrapped schemas as the keys and the envelope schemas as the values.  Then in `jsend_schema` check to see if `schema` is in the dictionary.  If is return the corresponding envelope schema otherwise create the envelope schema, add the mapping to the dictionary, and return the envelope schema.  

Also note that you probably want to set `key: fields.Nested(schema)`.

**Comment by lafrech** [comment]
@Paradoxis, are you still stuck with this or shall we close the issue?

**Comment by Paradoxis** [comment]
@lafrech still stuck, haven't been able to figure it out and had to put the feature as 'on hold'

**Comment by lafrech** [comment]
Closing this as pretty old and not much feedback. Feel free to comment and we can reopen.
