### ISSUE TITLE
discriminator support?

### ISSUE THREAD

**Issue by fingon** [marshmallow-code/apispec#46]
Swagger 2.0 has 'discriminator' field, which is essentially used to choose the schema to use based on contents of the field. At least apispec 0.6 does not have this (nor does actually marshmallow itself, +- marshmallow-polyfield which is similar but helps choose type of field instead of the whole object's schema).

Any plans on this?

**Comment by sloria** [comment]
There are no near-term plans for this, but I would certainly review a PR for it.

**Comment by lafrech** [comment]
Ideally, I would add

    discriminator = 'field_name'

to the `Meta` of the Schema.

But if I do that, I don't know where to get `'discriminator'` back. It is lost in [`SchemaOpts.__init__`](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/schema.py#L183) in Marshmallow, which only picks a whitelist of attributes.

Also, it is a bit misleading that [discriminator appears](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/swagger.py#L196) in [`_VALID_PROPERTIES`](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/swagger.py#L171), which is used in [field2property](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/swagger.py#L280) but not in [schema2parameters](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/swagger.py#L289). AFAIK, it is only useful for a schema, not for a field.

Right now, what I do is add `'x-discriminator': 'field_name'` when calling `definition` on my schema:

    api.definition('MySchema')(schema, **{'x-abstract': True, 'x-discriminator': 'kind'}

This works because I added a schema definition registration helper to my framework to pass `'x-'` attributes to the spec: https://github.com/Nobatek/flask-rest-api/blob/master/flask_rest_api/spec/plugin.py#L111

The whole inheritance mechanism is [not well defined in OpenAPI](https://github.com/OAI/OpenAPI-Specification/issues/403) yet so I only rely on `x-` properties.

**Comment by sloria** [comment]
This is now supported via the `extra_fields` parameter to `definition`:

```python
spec.definition('Pet', extra_fields={'discriminator': 'pet_type'})
```
