### ISSUE TITLE
How to generate global enum?

### ISSUE THREAD

**Issue by mlschneid** [marshmallow-code/apispec#474]
I'm interested in generating a global enum (ex Color) that I can reference in parameters.

Is this currently possible?

Example below:

```    
  paths:
      /products:
        get:
          parameters:
          - in: query
            name: color
            required: true
            schema:
              $ref: '#/components/schemas/Color'
          responses:
            '200':
              description: OK
    components:
      schemas:
        Color:
          type: string
          enum:
            - black
            - white
            - red
            - green
            - blue
```

**Comment by lafrech** [comment]
You can do it manually using the `APISpec.components.schema` method (or `APISpec.components.parameter` if you want to register a parameter instead).

If you're using marshmallow and you have a field with a OneOf validator and you'd like to use this field to generate the schema rather than build the schema manually, then I'm afraid you can't do that because the `MarshmallowPlugin` only works on schemas, not fields.

**Comment by mlschneid** [comment]
Thanks for the response. This should work out for me.
