### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/apispec#491]
Now that we're working on a new major apispec release, seems a good time as any to do this...

**Comment by sloria** [comment]
@lafrech @Bangertm any objections?

**Comment by sloria** [comment]
We can also probably drop support for Python 3.5. Usage is very low among marshmallow users (even lower than Python 2!): http://marshmallow.sloria.io/#ma2-vs-ma3-pyminor

**Comment by sloria** [comment]
Summoning @hugovk: slayer of python 2-compatible code

**Comment by hugovk** [comment]
I'll make a PR!

**Comment by lafrech** [comment]
No pb with dropping PY2.

https://pythonclock.org/

We run our apps on Debian. Buster is out and it ships PY3.7 but some apps still run on Stretch with PY3.5 and porting them to Buster is not absolutely trivial so if there's no great benefit from dropping 3.5, I'd rather keep it.

Since we allow ourselves more frequent major updates for apispec/webargs than for marshmallow, we can always drop it later on.

**Comment by hugovk** [comment]
I included dropping 3.5 in https://github.com/marshmallow-code/apispec/pull/492, but I don't see a great benefit so can adjust it tomorrow to only drop 2.7.

**Comment by sloria** [comment]
Yep, I'm fine with supporting 3.5 for now. Thanks @hugovk for working on this (again).
