### ISSUE TITLE
Default for schema fields.Date parameters not in API example values

### ISSUE THREAD

**Issue by max-gartz** [marshmallow-code/apispec#508]
If I set the default value in da Marshmallow schema string field (for example) I get this value in the example value in the documentation for the corresponding function in my swagger ui.

If I try the same with a marshmallow.fields.Date field, I always get todays date as the value in the example.

as an example I defined those two fields:     

```py
start_date = ma.fields.Date(required=True, default=date.today().replace(day=1))
end_date = ma.fields.Date(required=True, default=date.today().replace(day=1) + relativedelta(years=1))
```
This ends up to be :
  "start_date": "2019-10-04",
  "end_date": "2019-10-04",

in the generated example values in the request body.

Am I doing something wrong or is the default for date params simply always today() and does not consider the set default in the schema field?

Thanks a lot in advance.

**Comment by lafrech** [comment]
This is an apsipec question.

Did you mean to use `missing` rather than `default`? `missing` is used when deserializing while `default` is used when serializing.

Do you really want to set `date.today()` as a default or is it just a contrived example? If you want to use the date when the request is executed, you need to use a callable, or you'll get the date when the app is launched.

apispec automatically sets default values from `missing` when missing is not a callable. If missing is a callable, it can't do that so you need to specify the default value manually by adding a `doc_default` metadata in the field.

Lastly, examples can only be added manually. If you're seeing an example displayed in the UI, it is most likely because

- no default was set because you're using `default` rather than `missing`
- no example was set because you set none
- the UI uses today's date as an example (ReDoc does that, I don't know about Swagger-UI)

> If I set the default value in da Marshmallow schema string field (for example) I get this value in the example value in the documentation for the corresponding function in my swagger ui.

If you're using `default` rather than `missing`, this is surprising.

The best way to investigate is to consider the generated json spec, not the UI display.

**Comment by max-gartz** [comment]
Ah I see, I think I got something wrong then. It seems like swagger uses the first one of defined choices as a default as well... Since they coincided with the values I defined as default, I thought this was working. 
Thank you very much anyway, for mentioning missing, since this is actually what I was trying to define. I think I will settle for the current date then. Thanks for your help.

**Comment by lafrech** [comment]
Good. Closing this, then.
