### ISSUE TITLE
help with yaml in docstrings

### ISSUE THREAD

**Issue by grudelsud** [marshmallow-code/apispec#509]
hey guys

apispec looks really great, but I'm finding really hard to find any documentation on how to write docstrings that would produce something usable for things like https://github.com/Redocly/redoc

anyone here can point me in the right direction, please?

**Comment by grudelsud** [comment]
ok, after a little research I understand my previous question was quite shallow. After checking the source code, I've found

```python
def load_operations_from_docstring(docstring):
    """Return a dictionary of OpenAPI operations parsed from a
    a docstring.
    """
    doc_data = load_yaml_from_docstring(docstring)
    return {
        key: val
        for key, val in doc_data.items()
        if key in PATH_KEYS or key.startswith("x-")
    }
```

which I realise is defined as part of the OpenAPI specification, defined here: https://swagger.io/docs/specification/paths-and-operations/

maybe would be worth linking in the apispec docs and giving some explanation that the parser would just generate an output that must be compatible with the OpenAPI specs? or maybe it's already there and I missed it, apologies if that's the case.

**Comment by lafrech** [comment]
I'm not sure I understand the question. The point of apispec is to generate OpenAPI documentation (that can be used in ReDoc or Swagger-UI).

> A pluggable API specification generator. Currently supports the OpenAPI Specification (f.k.a. the Swagger specification).

apispec comes with optional support for YAML docstrings. The docs provide a docstring example : https://apispec.readthedocs.io/en/latest/.

The alternative to writing YAML docstrings is to call apispec functions directly with needed information. Since this can be cumbersome (it is the same information as in the docstring, but less practical to write), this is typically something a framework would do for you. For instance, when using [flask-smorest](https://github.com/marshmallow-code/flask-smorest), the user passes schemas to deserialize requests and serialize responses, and apispec is called automatically with necessary information to generate the API documentation.

**Comment by grudelsud** [comment]
100% agree with your comment @lafrech that calling apiscpec functions with needed information can be cumbersome. My question was mainly related to a difficulty in finding the right YAML specs in docstrings that would produce a sensible OpenAPI description. 

After I landed on the swagger.io YAML specs page, it all made sense, so I guess that just linking from the Apispec page to OpenAPI accepted formats would result in clearer documentation (although I might have missed the link if it's already there)

**Comment by lafrech** [comment]
Can you point us to the specific link you'd like to find in the docs?

**Comment by grudelsud** [comment]
I guess any of the pages describing the specs around this section https://swagger.io/docs/specification/basic-structure/

**Comment by lafrech** [comment]
That's the OpenAPI specification. Sure, we could point to it from the docs. But it is the page users should naturally turn to when searching for information about how to describe their API in OpenAPI format.

I mean there is nothing specific to apispec, here. If the docstring is passed more or less transparently, all the user needs to do is write valid OpenAPI descriptions, and that's up to him (and he should refer to the OpenAPI specs).

This said, I don't mind adding a like to [OpenAPI docs](https://swagger.io/docs/). And/or replacing the link to OpenAPI Github with a more relevant link to [OpenAPI website](https://swagger.io/).

**Comment by lafrech** [comment]
The relevant link would be https://swagger.io/resources/open-api/.

Let's stick to GitHub link. The OpenAPI website sometimes changes and linking to a page could break anytime.
