### ISSUE TITLE
get_random_pet() should be included in examples

### ISSUE THREAD

**Issue by hughesadam87** [marshmallow-code/apispec#577]
Was trying to copy and paste the frontpage example and the `get_random_pet()` function is not included.  Could this be added to the example or front page somehow so newbies can get started faster?  It's not 100% trivial to create a random `Pet` object that fits the nested `PetSchema`...

It would also be good to maybe include requirements.txt to have a complete working example.  Maybe put it in an `example` folder?

**Comment by Bangertm** [comment]
You don't need to implement the `get_random_pet` function to get the example working because the view function is never called. The body of `random_pet` is just shows generally how marshmallow would work in a flask application. Adding an implementation for `get_random_pet` might clutter the example because it is not strictly relevant to the way apispec works.

The only library dependencies are the ones explicitly imported at the top of the example.

**Comment by sloria** [comment]
Sorry--didn't mean to lock. I'm not entirely opposed to adding an `get_random_pet` to make the snippet runnable, so long as it doesn't hurt the understandability. In general we try to make the "splash" snippet concise.

**Comment by sloria** [comment]
@Bangertm has a good point, though--the app should run as is. Requesting the endpoint will error, but that doesn't seem important

**Comment by lafrech** [comment]
I also think the implementation is not relevant to the example snippet.
