### ISSUE TITLE
OpenAPI 3.1 support

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/apispec#579]
There's been a 3.1.0 RC release and they decided to make breaking changes.

https://github.com/OAI/OpenAPI-Specification/releases

It didn't go through all the changes yet to see if and how we are impacted.

At least, since they don't follow semver anymore and things can change in minor versions, we may have to modify some functions to pass the version object or string rather than just the major version as int.

Also I did a quick search to find an EOL for OAS v2 and I didn't find anything. Maybe there is no need for an EOL on a spec, as opposed to a code library.

**Comment by Bangertm** [comment]
I took a look at the breaking changes section: 
> The specification versioning no longer follows SemVer.
The nullable keyword has been removed from the Schema Object (null can be used as a type value).
exclusiveMaximum and exclusiveMinimum cannot accept boolean values (following JSON Schema).
Due to the compliance with JSON Schema, there is no longer interaction between required and readOnly/writeOnly in relation to requests and responses.
format (whether byte, binary, or base64) is no longer used to describe file payloads. As part of JSON Schema compliance, now contentEncoding and contentMediaType can be used for such specification.

Of these I think the only one that poses an issue for apispec is the nullable keyword being removed. Going forward it looks like JSON Schema indicates that a parameter is nullable via the type field like: 
```json
{
    "type": ["string", "null"]
}
```
So we will need to rework the way `field2nullable` works. Possibly combining it with `field2type_and_format`.

apispec doesn't use exclusiveMaximum or exclusiveMinimum so no issue there.

I don't think apispec does anything to tie required to readOnly/writeOnly.

Dealing with files is more of a web framework thing so that's probably left as a client responsibility.

**Comment by niraveen** [comment]
May I know when version OpenAPI 3.1.0 will be supported? I see webhook schema is added in 3.1.0

**Comment by lafrech** [comment]
No one is working on it at the moment to my knowledge.

Contributions welcome. If there's any change you need, feel free to discuss it here or in a dedicated issue.

**Comment by gwerbin** [comment]
> No one is working on it at the moment to my knowledge.
> 
> Contributions welcome. If there's any change you need, feel free to discuss it here or in a dedicated issue.

What do you think the difficulty level is for this task, for a new contributor? It seems like the list of changes is small, but there are always "gotchas" and an adjustment period for people who aren't already familiar with the code.

**Comment by Bangertm** [comment]
If it's just handling the the nullability item, I think that is pretty straight forward. At first blush I think it's just modifying or potentially combining two functions. It looks like there are already some version checks around nullability so this would be adding another case. Probably a good item for a new contributor 😉
