### ISSUE TITLE
flask-apispec support

### ISSUE THREAD

**Issue by kam193** [marshmallow-code/apispec#606]
Hi,

I want to kindly share here a some crucial needs from `flask-apispec`. I see projects are separated, but it seems they have strong connections, including contributors.

Since apispec 4.0, flask-apispec is broken (https://github.com/jmcarp/flask-apispec/issues/202). There are PRs with proposed solutions, but it looks like none from contributors had time to look at them. 

I would kindly ask for taking a look at those PRs/issue, since flask-apispec is still in use.

**Comment by sloria** [comment]
flask-apispec was developed independently of apispec. Neither I nor the original author of flask-apispec are using the project, which is why maintenance has slowed down despite apispec being active. I understand that slow development on the project is frustrating, but I unfortunately can't commit much time to it.

**Comment by kam193** [comment]
I fully understand. Since I think it's an important problem, I decided to try to ask for help. Thank you for the answer!
