### ISSUE TITLE
Minimum/maximum date is not jsonschema compliant

### ISSUE THREAD

**Issue by mdantonio** [marshmallow-code/apispec#614]
I'm using flask-apispec (but I think that the issue is related to apispec) to generate a swagger 2.0 schema from  webargs/marshmallow models that include datetimes with min/max boundaries like this:

```
mydate = fields.DateTime(
    required=True,
    validate=validate.Range(
        max=datetime.now(pytz.utc).replace(hour=23, minute=59, second=59),
        min=datetime(1900, 1, 1, tzinfo=pytz.utc),
        max_inclusive=True
    )
)
```

The generated json shema is:

```
"mydate": {
    "format": "date-time",
    "maximum": "Tue, 08 Dec 2020 23:59:59 GMT",
    "minimum": "Mon, 01 Jan 1900 00:00:00 GMT",
    "type": "string"
},
```

But when I run schemathesis on the generated schema I obtain a validation error

```
E   jsonschema.exceptions.ValidationError: 'Tue, 08 Dec 2020 23:59:59 GMT' is not of type 'number'
E  
E   Failed validating 'type' in schema['properties']['definitions']['additionalProperties']['properties']['properties']['additionalProperties']['properties']['maximum']:
E       {'type': 'number'}
E  
E   On instance['definitions']['Input']['properties']['mydate']['maximum']:
E       'Tue, 08 Dec 2020 23:59:59 GMT'
```

Schemathesis is right, because minimum and maximum values are expected to be "JSON numbers" (https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.1.3) and not datetimes

On the other side having min and max date validation is a very appreciated feature, so the option to avoid to set these boundaries on the models is not really feasible for my use cases. Furthermore the use of schemathesis is very helpful for my test suite and I would like to continue to use it.

Is there something that I can modify / configure to obtain jsonschema compliant models from webargs/marshmallow schema with datetimes min/max values?

Or maybe is there something that apispec could fix to obtain the result? (for example convert min/max datetimes into timestamps? Having a number should be adherent to the schema specification)

If not possible, I could try to open an issue on schemathesis to ask for some compatibility fixes. They already include [compatibility fixes for fastapi](https://schemathesis.readthedocs.io/en/stable/compatibility.html#using-fastapi) (that by using pydantic produces Draft 7 compatible schemas, while schemathesis validates against Draft 4 and Wright Draft 00) so maybe they would be interested in adding some compatibility fixes also for apispec. But in this case I would like to ask for your help to support the request by providing your motivations for not meeting the specifications or other information that they could ask to me.

I really thank you for your help

**Comment by Bangertm** [comment]
It seems per [this question](https://github.com/OAI/OpenAPI-Specification/issues/2138) in the OpenAPI specification that `minimum` and `maximum` keywords are not valid on string fields even when using the date-time format. 

So it also would not be valid to convert the `datetime` validators into a timestamp. To get valid OpenAPI for that field we would probably need to suppress adding range validation to the spec for fields that are not numbers. Arguably suppressing non-standard output is worse from a user perspective, but obviously creates issues with other tooling.

**Comment by mdantonio** [comment]
Very clear, thank you
Since no changes are possible on apispec side I will open an issue on schemathesis to request for some compatibility fix.
Are you available to support my request there, if some information about apispec (and about your motivation) will be requested?

**Comment by Stranger6667** [comment]
Hi, the Schemathesis author here :)

> Arguably suppressing non-standard output is worse from a user perspective, but obviously creates issues with other tooling.

The Open API spec [supports extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#specification-extensions) via the `x-`  prefix (it is also supported for Open API 2.0). For example, `x-maximum` will be perfectly valid from the spec perspective for [schemas](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schemaObject) and probably won't change much for the users (it is a completely baseless assumption from my side). What do you think about this approach?

> I will open an issue on schemathesis to request for some compatibility fix.

We can totally do that, but I'd be happy to discuss other options first - Schemathesis might support such extension as mentioned above instead of compatibility fix, and actually validate values.

**Comment by lafrech** [comment]
I was about to suggest using a `x-` extension for that.

The only regression case I can think of would be if an existing tool currently displays min/max for non-number fields in spite of those not being spec compliant. Only custom tools would display `x-minimum` / `x-maximum`

But a spec is a spec and apispec ought to conform to it.

--------------------------

It might be a bit challenging to achieve because what we call "attribute functions" are independent. `field2type_and_format` determines the type, `field2range` determines the range, etc. We could let `field2type_and_format` execute first, then pass type and format to other functions.

**Comment by mdantonio** [comment]
> We can totally do that, but I'd be happy to discuss other options first

This is exactly why I was asking the support of apispec authors for the issue that I'd open on schemathesis repo...  I'm very glad that you joined this discussion!

Thank you everybody

(for what it matters, I would be very fine with the x- solution)
