### ISSUE TITLE
TimeDelta fields not generating useful documentation

### ISSUE THREAD

**Issue by camercu** [marshmallow-code/apispec#631]
Documentation for `marshmallow.fields.TimeDelta` is not capturing anything about the field type except the description. Under the hood, Marshmallow treats it as an `int` that gets converted to a `datetime.timedelta` on deserialization.

Here is the line from the schema declaration:
```py
    uptime = fields.TimeDelta(precision="minutes", required=False, metadata={"description":"running time"})
```

Example output of "uptime" field (type TimeDelta) from openapi.json generated by flask-smorest:
```json
{
  "uptime": {
    "description": "running time"
  }
}
```

And here is a screen grab of the Swagger UI:
![Capture](https://user-images.githubusercontent.com/6279092/105771793-21cb3800-5f2f-11eb-8b77-e5ad9a2f03ae.PNG)

I think it should be treated as an number, with the precision string spelled out in the documentation. Is there a way to add this?

**Comment by lafrech** [comment]
Transferring to apispec as this is where it happens.

Indeed, we ought to add TimeDelta to `DEFAULT_FIELD_MAPPING` https://github.com/marshmallow-code/apispec/blob/5762c831fccf9d8dedcdfb901d106c02addc278b/src/apispec/ext/marshmallow/field_converter.py#L21-L37

I suppose we'd stick to type = integer and no format, because the OpenAPI spec doesn't define more than this.

PR welcome, of course.

Expressing the fact that it is a timedelta and the precision can be done in the description. Or in a custom field using a custom field converter. If there is a widely spread way of expressing it using something like `x-precision`, we could add it to apispec.
