### ISSUE TITLE
[marshmallow plugin] Inspect validators

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/apispec#66]
Many of marshmallow's validators can be inspected to provide additional data when constructing OpenAPI entities.

``` python
from marshmallow import fields, validate
from apispec.ext.marshmallow.swagger import field2property

field = fields.Int(validate=validate.Range(min=3, max=42))

prop = field2property(field)
assert prop['minimum'] == 3
assert prop['maximum'] == 42
```

**Comment by deckar01** [comment]
There are 3 objects in the OpenAPI spec that support validation fields:
- [Parameter](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object)
- [Items](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#items-object)
- [Header](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#header-object)

The header object only supports simple types, so there is no marshmallow schema to validate.

Matching validators:

| Marshmallow Validator | OpenAPI Validator |
| --- | --- |
| Email | pattern (specific) |
| Equal | enum (single) |
| Length (list?) | minItems, maxItems |
| Length (*) | minLength, maxLength |
| OneOf | enum |
| Range | minimum, maximum |
| Regexp | pattern |
| URL | pattern (specific) |

Unsupported marshmallow validators:

| Marshmallow Validator | OpenAPI Validator |
| --- | --- |
| ContainsOnly | (maybe enum?) |
| NoneOf |  |
| Predicate |  |
| Validator | (user defined?) |

It should be possible to design this mapping in such a way that user defined marshmallow validators could register their own OpenAPI validator mapping with apispec.

Unsupported OpenAPI validators:

| Marshmallow Validator | OpenAPI Validator |
| --- | --- |
|  | exclusiveMinimum |
|  | exclusiveMaximum |
|  | uniqueItems |
|  | multipleOf |

Maybe there should be an issue for marshmallow to support these validators, so that there can be a subset of marshmallow validators that completely cover the OpenAPI spec.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object
https://marshmallow.readthedocs.io/en/latest/api_reference.html#module-marshmallow.validate

**Comment by lafrech** [comment]
`allow_none` is somehow related, although it is not a `Validator`.

It would map to `nullable`, except [`nullable` does not exist... yet](https://github.com/OAI/OpenAPI-Specification/issues/229). There seems to be a wide consensus upon the use of `x-nullable` until `nullable is added` (OpenAPI 3). It has been [integrated in ReDoc](https://github.com/Rebilly/ReDoc/pull/95), for instance.

Should we introduce `x-nullable` in `field2property`?

Right now, the workaround is to specify both `allow_none=True` and `x_nullable=True` in the model.

**Comment by sloria** [comment]
Closing this for now. Feel free to reopen if this requires further discussion.
