### ISSUE TITLE
dump_only attributes passed in Meta options are not marked as readOnly

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/apispec#84]
Reported by @lafrech in https://github.com/marshmallow-code/apispec/pull/81#issuecomment-233417809:

---

I noticed this only adds readOnly if the field was provided dump_only attribute directly. If the field appears in the dump_only list in Meta, readOnly is not added.

Is this known/intended?

More precisely, it "does not work" if spec.definition is passed a marshmallow.schema.SchemaMeta but it "works" if it is passed a Schema instance:

class GistSchema(ma.Schema):
    id = ma.fields.Int()
    content = ma.fields.Str()

```
class Meta:
    dump_only = ('content',)
```
# readOnly not added

spec.definition('Gist', schema=GistSchema)
# readOnly added

spec.definition('Gist', schema=GistSchema())
I just begun experimenting with apispec and I'm not sure passing an instance is the right thing to do. In the docs, a SchemaMeta is passed.

**Comment by sloria** [comment]
The workaround for this is to pass a schema instance rather than a class:

```python
spec.definition('Gist', schema=GistSchema())
```

because the `dump_only` attribute gets set on the fields upon schema instantiation.

**Comment by lafrech** [comment]
Yes.

I had a look at this issue when it was submitted and didn't find any obvious solution.

This workaroud works but it breaks [schema resolving in marshmallow extension](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/__init__.py#L134). The mechanism relies on Schema classes being stored, not instances.

I would like to suggest the following change to `schema_definition_helper` in marshmallow extension, so that 

- the schema instance is used to create the json description (this workaround)
- the schema class is stored (needed for further reference resolving)

```python
def schema_definition_helper(spec, name, schema, **kwargs):
    """Definition helper that allows using a marshmallow
    :class:`Schema <marshmallow.Schema>` to provide OpenAPI
    metadata.

    :param type schema: A marshmallow Schema class or instance.
    """

    if isinstance(schema, type):
        schema_cls = schema
        schema_instance = schema()
    else:
        schema_cls = type(schema)
        schema_instance = schema

    # Store registered refs, keyed by Schema class
    plug = spec.plugins[NAME]
    if 'refs' not in plug:
        plug['refs'] = {}
    plug['refs'][schema_cls] = name
    return swagger.schema2jsonschema(schema_instance, spec=spec, name=name)
```

Allowing an instance to be passed to the definition helper is not related to the workaround and could be done anyway.

What do you think, @sloria?

**Comment by lafrech** [comment]
On second thought, I'm mixing two issues here.

I just sent a PR to let `schema_definition_helper` pass  `schema2jsonschema` a Schema instance rather than a class.

The tests fail because this change breaks the use case where `schema_definition_helper` is passed a Schema instance.

AFAIU, there is an inconsistency between the [tests](https://github.com/marshmallow-code/apispec/blob/dev/tests/test_ext_marshmallow.py#L27) and the [docs](https://apispec.readthedocs.io/en/latest/api_ext.html#apispec.ext.marshmallow.schema_definition_helper) / [comments in the code](https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/marshmallow/__init__.py#L42). The docs say we should pass a Schema class, but we test that both a class and an instance can be passed.

If we want to be able to pass both, then the comments/docs should be updated. And my code proposal above may be relevant.

**Comment by sloria** [comment]
@lafrech Thank you for looking into this. I think you are correct re: the docs/comments being incorrect. Users should be able to pass either a class or instance, and I think your solution in your previous comment should work.

**Comment by lafrech** [comment]
Thank you for the feedback @sloria. I sent a new PR.
