### ISSUE TITLE
How to integrate with swagger ui

### ISSUE THREAD

**Issue by ishankhare07** [marshmallow-code/apispec#91]
I would like to understand how does this work with swagger. I generated the `swagger.json` by writing output of `spec.to_dict()` and then opening the `swagger.json` file from `swagger ui`. There are no errors reported and neither and documentation generated.

> Note: is it because everything in my `spec` is just `marshmallow schema` and `NO api endpoints`

**Comment by lafrech** [comment]
You may want to share your swagger.json here so that people can figure out which part is missing.

You may also have a look at the swagger.json file from the petstore example ([UI](http://petstore.swagger.io/), [json file](http://petstore.swagger.io/v2/swagger.json) for an example of a correct spec file.

**Comment by ishankhare07** [comment]
@lafrech after verify my swagger.json at http://editor.swagger.io/#/ I get and error `Definition is not used: #/definitions/Message Schema`

**Comment by sloria** [comment]
`apispec` is only responsible for generating the data that would be rendered to `swagger.json` or `swagger.yaml`. It does not generate UI. Frontends like Swagger-UI would consume the rendered spec generated by apispec.
